### ISSUE TITLE
Text parsed after closing <sub> tag in SSML mistakenly uses text in alias

### ISSUE THREAD

**Issue by lpalombo** [rhasspy/gruut#16]
I'm working on a project that implements the latest version of OpenTTS. Our only option for correcting pronunciation is to use the `<sub alias="">` tag, so until this is fixed that functionality is also missing from OpenTTS.

fixed in #15 

test:
```bash
echo '<speak><s><sub alias="to mah to">tomato</sub></s><s>this text should be parsed, but it isn't</s></speak>' | gruut --language en-us --ssml | jq --raw-output '.words[].text'

# should return
to
mah
to
this
text
should
be
parsed
,
but
it
isnt

# instead returns
to
mah
to
to
mah
to
```

**Comment by synesthesiam** [comment]
I've merged the pull request (thank you!). I'll push an updated version and re-build the OpenTTS images.

**Comment by synesthesiam** [comment]
OpenTTS images have been updated
